---
output:
  pdf_document: default
  html_document: default
---
---
title: "STAT 536 HW 1 Report"
author: "Ty Hawkes and Brigg Trendler"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r, include = FALSE, message = FALSE}
# Data & Packages
library(tidyverse)

# Data
df <- vroom::vroom("Rivers.csv")
```


## Abstract

## 1. Introduction: Problem Statement and Understanding

Rivers are responsible for carrying water and nutrients to various parts of the earth.
Many animals, including humans, rely on rivers and the life they bring to thrive in otherwise
uninhabitable areas.
In this project, we work to analyze how various factors (human, river network, and climate)
impact the overall river flow in the Rocky Mountain area.

Through an initial exploratory data analysis, we found that we have 95 covariates and
102 observations.
This means, should we create a linear regression model with every variable, the model
would likely be severely overfit, which would lead to several potential problems,
including multicollinearity, high variance in coefficients, and interpretability issues.

The data set also contains monthly averages for precipitation, temperature, and cumulative precipitation,
as well as annual averages for those same variables.
This is potentially problematic because including both the yearly and monthly
averages would introduce multicollinearity into the model.
Furthermore, some of the variables are direct linear combinations of others.
For example, the variable bio7 gives the annual temperature range, given by
subtracting the max temperature from the minimum, both of which are stored as
bio5 and bio6.
Thus we want to avoid including these in our model simultaneously.

In this project, we hope to find a predictive model for river flow based on
the given variables while simultaneously avoiding incorporating the aforementioned
problems into our model.

## 2. Methodology

### 2.1 Proposed Methods

To combat the high dimensionality of our data set, we propose two models: a linear
regression model constructed from a LASSO regularization, and a linear regression
model created from a bi-directional selection algorithm using the AIC as a scoring metric.

LASSO regularization helps reduce dimensionality selecting the most relevant predictors.
It improves interpretability by producing a sparse model and reduces overfitting.
However, it can introduce bias into coefficient estimates, and can struggle 
when trying to handle highly correlated variables.
In the context of the problem of this case study, a model built by LASSO would solve
the dimensionality problem, however the colinearity between variables might pose a problem
for this method.

A forward and backward selection algorithm balances model fit and complexity.
It also automates variable selection and has the advantage of navigating correlated
predictors better than a pure forward or pure backward selection algorithm.
Unfortunately, it is a greedy algorithm, meaning it may not find the best
model.
It also does not handle multicollinearity well and can be computationally expensive.
A forward and backward selection model in the context of this problem would also
solve the dimensionality issue.

In both cases, we will need to check the classic LINE assumptions when using
linear regression: linearity, independence, normally distributed errors, and equal variance.

### 2.2 Model Evaluation

## 3. Results

### 3.1 What are the biggest climate / river network / human factors that impact overall river flow?

### 3.2 How well do the factors you listed in #1 explain overall flow?

### 3.3 How predictive of overall flow are these identified factors?

## 4. Conclusions

## Teamwork

